# Generated by Django 5.0.4 on 2024-11-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tipo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de crédito/débito'), ('efectivo', 'Efectivo'), ('mp', 'Mercado Pago')], default='tarjeta', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
