# Generated by Django 3.0.6 on 2024-09-26 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDjango', '0001_initial'),
    ]

    operations = [
    ]
